# Important manual steps required:
#
# pacman -Syu
# pacman -S python2
# DO NOT LOG OUT FROM root OR YOU WILL GET LOCKED OUT!
# run this playbook `ansible-playbook -i inventory --ask-pass base_arch.yml`
# passwd joe
# if you logged out from root. Stick the sd card in anouther machine and edit
# /etc/ssh/sshd_config to comment out `PasswordAuthentication no`

- name: set the timezone
  command: timedatectl set-timezone Europe/London

- name: install necessary or useful packages
  pacman: name={{ item }} state=installed
  with_items:
    - sudo
    - vim
    - wget
    - tree

- name: configure sudo
  lineinfile: >
    dest=/etc/sudoers
    regexp="joe ALL"
    line="joe ALL=(ALL) ALL"
    state=present
    validate='visudo -cf %s'

- name: Add joe user
  user: name=joe groups=users shell=/bin/bash

- name: Give joe his authorized keys file
  authorized_key: >
    user=joe
    key="{{ lookup('file', '/Users/joe/.ssh/id_rsa.pub') }}"

- name: Remove ability for root user to login over ssh
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^#PasswordAuthentication"
    insertafter="^#PasswordAuthentication"
    line="PasswordAuthentication no"

- name: Install dev tools
  pacman: name=base-devel state=installed update_cache=yes

- name: Install packer for easy AUR installs
  pacman: name=packer state=installed

- name: Install vim
  pacman: name=vim state=installed
