- name: install mpd & mpc
  apt: name={{ item }} update_cache=true
  with_items:
    - mpd
    - mpc

- name: configure wireless
  copy: src=interfaces dest=/etc/network/interfaces mode=0644 backup=true

- name: reload networking service
  service: name=networking state=reloaded

- name: create auto-play script
  copy: src=play.sh dest=/home/pi/play.sh mode=0644

- name: auto-play stream on reboot via cron
  cron: name="auto play music stream" special_time=reboot job="/bin/bash /home/pi/play.sh"
