- name: install mpdscribble
  apt: name=mpdscribble update_cache=true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install binutils
  pacman: name=binutils
  when: ansible_distribution == 'Archlinux'

- name: install mpdscribble
  command: packer -S --noconfirm mpdscribble
  when: ansible_distribution == 'Archlinux'
  # FIXME arch=('armv6h') is missing in the default PKGBUILD so I ran this manually
  ignore_errors: true

- name: configure mpdscribble with last.fm credentials
  template: >
    src=mpdscribble.conf dest=/etc/mpdscribble.conf
    backup=yes mode=0640

- name: enable mpdscribble daemon
  template: >
    src=mpdscribble dest=/etc/default/mpdscribble
    backup=yes mode=0644
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: enable mpdscribble daemon
  template: >
    src=mpdscribble.service dest=/usr/lib/systemd/system/mpdscribble.service
    mode=0644
  when: ansible_distribution == 'Archlinux'

- name: enable mpdscribble daemon
  command: systemctl enable mpdscribble
  when: ansible_distribution == 'Archlinux'

- name: restart mpdsribble
  service: name=mpdscribble state=restarted
