- name: create mothership init.d template
  template: src=init.d-mothership dest=/etc/init.d/mothership mode=0755
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: create mothership systemd unit
  template: src=mothership.service dest=/usr/lib/systemd/system/mothership.service mode=0644
  when: ansible_distribution == 'Archlinux'

- name: allow mothership to listen in port 80
  command: setcap cap_net_bind_service=ep /usr/bin/mothership

- name: enable mothership daemon
  command: systemctl enable mothership
  when: ansible_distribution == 'Archlinux'

- name: start mothership daemon
  action: service name=mothership state=started
