- name: create mothership init.d template
  template: src=init.d-mothership dest=/etc/init.d/mothership mode=0755
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: create mothership systemd unit
  template: src=mothership.service dest=/usr/lib/systemd/system/mothership.service mode=0644
  # TODO: use more specific arch identifier when anible is updated with this
  # patch https://github.com/mantiz/ansible/commit/5efc4efca7288f072028d1a13e5d0d731f0b7a8f
  when: ansible_distribution == 'NA'

- name: allow mothership to listen in port 80
  command: setcap cap_net_bind_service=ep /usr/bin/mothership

- name: enable mothership daemon
  command: systemctl enable mothership
  # TODO: use more specific arch identifier when anible is updated with this
  when: ansible_distribution == 'NA'

- name: start mothership daemon
  action: service name=mothership state=started
