- name: enable cron
  lineinfile: >
    dest=/var/www/command/orion_optimize.sh
    backup=true
    regexp="^(killall.*cron)"
    line="#\1"
    backrefs=true

- name: copy check-system script
  copy: src=check-system.sh dest=/root/check-system.sh mode=0744

- name: copy bbc radios script
  copy: src=bbc.sh dest=/root/bbc.sh mode=0755

- name: create bbc.sh cron
  cron: name="update bbc feeds" hour="*/1" job="/bin/bash /root/bbc.sh"
