- name: configure RSS feeds
  copy: backup=true src=RssFeeds.xml dest=/home/pi/.xbmc/userdata/ mode=0644

- name: configure network passwords
  template: backup=true src=passwords.xml dest=/home/pi/.xbmc/userdata/ mode=0644

- name: configure sources
  copy: backup=true src=sources.xml dest=/home/pi/.xbmc/userdata/ mode=0644

# For some unknown reason, a straight-copy of guisettings.xml just hangs
- name: configure GUI settings | copy template
  copy: src=guisettings.xml dest=/home/pi/.xbmc/userdata/gui.xml mode=0644
- name: configure GUI settings | remove old
  command: rm /home/pi/.xbmc/userdata/guisettings.xml
  ignore_errors: true
- name: configure GUI settings | apply new
  command: mv /home/pi/.xbmc/userdata/gui.xml /home/pi/.xbmc/userdata/guisettings.xml
